# Generated by Django 5.0 on 2023-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего изменения')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('temperature', models.IntegerField(null=True, verbose_name='Текущая температура (°C)')),
                ('wind_speed', models.IntegerField(null=True, verbose_name='Скорость ветра (м/с)')),
                ('pressure', models.IntegerField(null=True, verbose_name='Атмосферное давление (мм. рт.ст.)')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
            },
        ),
    ]
